#!/bin/sh
dunstify -h int:value:$(brightnessctl i | head -2 | grep % | awk '{print $4}' | sed 's/[^0-9]*//g') 'Brightness : '$(brightnessctl i | head -2 | grep % | awk '{print $4}' | sed 's/[^0-9]*//g')'%'
